### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by jaredpalmer** [aws-containers/hello-app-runner#2]
<img width="1290" alt="Screen Shot 2021-05-19 at 5 06 14 PM" src="https://user-images.githubusercontent.com/4060187/118884479-86d2e100-b8c4-11eb-800f-863fc5d2bd66.png">
I just cloned this repo and tried to deploy it to App Runner via the instructions in the docs. Please advise.

**Comment by rothgar** [comment]
That looks like it's health checking on port 8080 instead of 8000. Can you try deploying again with port 8000?
