### ISSUE TITLE
Error in assuming access role .. AppRunnerECRAccessRole

### ISSUE THREAD

**Issue by robmarkcole** [aws-containers/hello-app-runner#3]
Hi
I've selected the option to have App Runner create a role for accessing private ECR but then the error is raised. Any advice?

**Comment by nauco** [comment]
I went through the same thing.
I received deployment log.
 "[AppRunner] Failed to pull your application image. Be sure you configure your service with a valid access role to your ECR repository."
Even I provided App Runner with an access role.

**Comment by kzima** [comment]
I get this same error message:
"[AppRunner] Failed to pull your application image. Be sure you configure your service with a valid access role to your ECR repository."

The problem:
Service running in us-west-2 cannot pull from ECR image in ap-southeast-2 region.

Solution:
Create ECR in the same region as App Runner Service.

Not sure what's wrong, but I would expect App Runner to be able to pull from any region's ECR.

I hope this helps.

**Comment by toricls** [comment]
Hi @kzima, I successfully pulled and run my ~~cross-region (and also~~ cross-account ~~)~~ images on App Runner.
Could you possibly share your policy document for the ECR repository in `ap-southeast-2` region? (Make sure that all AWS account IDs and user names are masked before putting it here)

Edit - My bad it's cross-account but not cross-region...

**Comment by rothgar** [comment]
Haven't heard back for a while so going to close out this ticket.
