### ISSUE TITLE
boto3 NoCredentialsError() and How to use print to log (Python) 

### ISSUE THREAD

**Issue by Jun711** [aws-containers/hello-app-runner#8]
Hi, I encountered some issues and need some help

1) I am using boto3 to access s3. I added permission to access s3 to the app runner role but when I got NoCredentialsError. Do I have to hardcode my credentials?
<img width="634" alt="Screen Shot 2021-09-17 at 7 13 11 PM" src="https://user-images.githubusercontent.com/6880939/133868954-42d46a3b-1948-479a-9211-2e14970c42fc.png">

2) my python print statements in the flask app don't seem to be passed to the stdout. Do I have to use logging instead?

**Comment by rothgar** [comment]
Hey Jun711,

You probably want to open a ticket with the app-runner-roadmap and not here in the hello example application. https://github.com/aws/apprunner-roadmap/issues
